embedder:
    azure:
        model: ""
        endpoint: ""
        api_key: ""
        api_version: ""
    lmstudio: 
        model: ""
        endpoint: ""
        
vector_db:
    weaviatelocal:
        collection: ""
        top_k: 5
        alpha: 0.3
    mongodb:
        url: ""
        db_name: ""
        collection_name: ""

chunker:
    fixed:
        overlap: 20
        chunk_size: 250
    semantic: {} 

llm:
    azure:
        model: ""
        api_key: ""
        endpoint: ""
        api_version: ""
    lmstudio:
        model: ""
        endpoint: ""
document:
    azure: {}
    docling: {}
    
           
